### ISSUE TITLE
Unexpected behaviour with first task in "Tasks" demo

### ISSUE THREAD

**Issue by anibali** [unpoly/unpoly-demo#12]
I have noticed buggy behaviour in the live version of the "Tasks" demo: https://demo.unpoly.com/tasks. Steps to reproduce:

1. Click "edit" on any task after the first.
2. Click "Save".
3. Click "edit" again.
4. The first task will change to the editing state and have its content replaced.

![Browser recording](https://github.com/unpoly/unpoly-demo/assets/226707/ce00c8c5-ee8b-45fc-a8ab-52c84a1ba639)

Tested in Firefox 114.

**Comment by adam12** [comment]
Thanks for the report. I can confirm the same functionality on Chrome.

I think it's the revalidation functionality somehow not having any context of the `:origin`, so it attempts to match `.task` and finds the first one (not the closest one).

**Comment by hpvd** [comment]
with latest update on base of v3.5, this seems to be fixed. Tested with FF120 and chrome

**Comment by adam12** [comment]
> with latest update on base of v3.5, this seems to be fixed. Tested with FF120 and chrome

Confirmed, thanks.
