### ISSUE TITLE
Project deletion from modal seems broken

### ISSUE THREAD

**Issue by apollo13** [unpoly/unpoly-demo#4]
Steps to reproduce:

 * go to https://demo.unpoly.com/projects
 * click on any project 
 * click `delete`
 
the modal now shows all companies. It should (imo) close the modal and go back to the previous projects page (preferably with a flash message that the project was removed successfully) and update the projects page to no longer include that project.

**Comment by adam12** [comment]
I agree it feels off. I wonder if we should redirect to `projects_path` here instead.

https://github.com/unpoly/unpoly-demo/blob/f33743ecda448c0bb193138701da8b5dfb696f93/app/controllers/projects_controller.rb#L35

**Comment by apollo13** [comment]
That would be a band-aid at least. From an UX perspective I think it should get closed and the user should somehow be informed about it. I know that those issues might seem minor, but it would nicely show how to properly use unpoly
